# Generated by Django 4.2.7 on 2023-11-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('children_stat', models.BooleanField(default=False)),
                ('children', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дети')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['name', 'age'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hw_23Nov.human', verbose_name='ФИО Родителя')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
                'ordering': ['name', 'parent'],
            },
        ),
    ]
