# Generated by Django 5.0.1 on 2024-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementer', models.CharField(max_length=100, verbose_name='Исполнитель')),
                ('author', models.CharField(max_length=100, verbose_name='Автор задачи')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('deadline', models.DateTimeField(db_index=True, verbose_name='Срок исполнения')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-published'],
            },
        ),
    ]
