# Generated by Django 5.0.1 on 2024-03-09 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedEditionIcecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тороговое наименование')),
                ('fabricator', models.CharField(max_length=40, verbose_name='Производитель')),
                ('composition', models.CharField(blank=True, max_length=500, null=True, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('package', models.CharField(choices=[('cup', 'стаканчик'), ('cone', 'рожок'), ('brick', 'брикет'), ('tube', 'туба '), ('box', 'коробка'), ('pouch', 'пакетик'), ('foil', 'фольга'), ('plastic_container', 'пластиковый контенер'), ('paper container', 'бумажный контенер'), ('balls', 'шарик')], default='balls', max_length=20, verbose_name='Упаковка')),
                ('weight', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Вес нетто')),
                ('expiration_date_in_days', models.IntegerField(default=30, verbose_name='Срок употребления')),
                ('vegan', models.BooleanField(default=False, verbose_name='Веганское')),
                ('sugar_free', models.BooleanField(default=False, verbose_name='Без добавления сахара')),
                ('theme', models.CharField(max_length=50, verbose_name='Тематика')),
                ('season', models.CharField(max_length=50, verbose_name='Сезон/Праздник')),
                ('sale_start_date', models.DateField(verbose_name='Дата начала продаж')),
                ('sale_end_date', models.DateField(verbose_name='Дата окончания продаж')),
                ('unique_flavors', models.TextField(help_text='Перечислите уникальные вкусы этой серии', verbose_name='Уникальные вкусы')),
            ],
            options={
                'verbose_name': 'Ограниченная серия мороженого',
                'verbose_name_plural': 'Ограниченная серия мороженого',
            },
        ),
        migrations.CreateModel(
            name='Subscribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, verbose_name='Mейл')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор задачи')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('deadline', models.DateField(db_index=True, verbose_name='Срок исполнения')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('n', 'Не начато'), ('d', 'Исполнено'), ('p', 'На исполнении')], default='n', max_length=1, verbose_name='Статус')),
                ('done_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата исполнения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-status', '-deadline'],
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование продавца')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер для связи')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendors_Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('icecream_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskBoard.limitededitionicecream')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskBoard.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='vendors',
            name='icecream_pl',
            field=models.ManyToManyField(through='TaskBoard.Vendors_Icecream', to='TaskBoard.limitededitionicecream'),
        ),
    ]
