# Generated by Django 5.0.1 on 2024-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-deadline'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('n', 'Не начато'), ('d', 'Исполнено'), ('p', 'На исполнении')], default='n', max_length=1),
        ),
    ]
