# Generated by Django 5.0.1 on 2024-03-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания продаж'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='sale_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала продаж'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сезон/Праздник'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='sugar_free',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Без добавления сахара'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='unique_flavors',
            field=models.TextField(blank=True, help_text='Перечислите уникальные вкусы этой серии', null=True, verbose_name='Уникальные вкусы'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='vegan',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Веганское'),
        ),
    ]
