# Generated by Django 5.0.1 on 2024-03-09 16:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0002_alter_limitededitionicecream_sale_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tasks',
            managers=[
                ('actions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='sugar_free',
            field=models.BooleanField(default=False, verbose_name='Без добавления сахара'),
        ),
        migrations.AlterField(
            model_name='limitededitionicecream',
            name='vegan',
            field=models.BooleanField(default=False, verbose_name='Веганское'),
        ),
    ]
