# Generated by Django 5.0.1 on 2024-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0002_alter_tasks_options_tasks_description_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='done_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(db_index=True, verbose_name='Срок исполнения'),
        ),
    ]
