# Generated by Django 5.0.1 on 2024-03-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0003_alter_tasks_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
