# Generated by Django 5.0.1 on 2024-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0003_tasks_done_date_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-status', '-deadline'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('n', 'Не начато'), ('d', 'Исполнено'), ('p', 'На исполнении')], default='n', max_length=1, verbose_name='Статус'),
        ),
    ]
