# Generated by Django 5.0.1 on 2024-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0005_subscribes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Тороговое наименование')),
                ('fabricator', models.CharField(max_length=40, verbose_name='Производитель')),
                ('composition', models.CharField(blank=True, max_length=500, null=True, verbose_name='Состав')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('package', models.CharField(choices=[(None, 'Выберите тип упаковки'), ('cup', 'Cup'), ('cone', 'Cone'), ('brick', 'Brick'), ('tube', 'Tube'), ('box', 'Box'), ('pouch', 'Pouch'), ('foil', 'Foil'), ('plastic_container', 'Plastic Container'), ('paper container', 'Paper Container'), ('balls', 'Balls')], default='balls', max_length=20, verbose_name='Упаковка')),
                ('weight', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='Вес нетто')),
                ('expiration_date_in_days', models.IntegerField(default=30, verbose_name='Срок употребления')),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженое',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='tasks',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='implementer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель'),
        ),
    ]
