# Generated by Django 5.0.1 on 2024-02-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0007_alter_icecream_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='package',
            field=models.CharField(choices=[('cup', 'стаканчик'), ('cone', 'рожок'), ('brick', 'брикет'), ('tube', 'туба '), ('box', 'коробка'), ('pouch', 'пакетик'), ('foil', 'фольга'), ('plastic_container', 'пластиковый контенер'), ('paper container', 'бумажный контенер'), ('balls', 'шарик')], default='balls', max_length=20, verbose_name='Упаковка'),
        ),
    ]
