# Generated by Django 5.0.1 on 2024-03-03 16:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0008_alter_icecream_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(error_messages={'invalid': 'Введите корректный адрес электронной почты'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='\\w[\\w\\.-]*\\w+@\\w[\\w\\.]*\\.[a-zA-Z]{2,3}')])),
                ('birth_date', models.DateField()),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование продавца')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('number', models.CharField(max_length=200, verbose_name='Номер для связи')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activated', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendors_Icecream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('icecream_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskBoard.icecream')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskBoard.vendors')),
            ],
        ),
        migrations.AddField(
            model_name='vendors',
            name='icecream_pl',
            field=models.ManyToManyField(through='TaskBoard.Vendors_Icecream', to='TaskBoard.icecream'),
        ),
    ]
