# Generated by Django 5.0.1 on 2024-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0009_clients_vendors_advuser_vendors_icecream_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер для связи'),
        ),
    ]
